// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ImportOZ$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ImportOZ";
  readonly sourceName: "contracts/ImportOZ.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea26469706673582212206ab8317330cd83ba3ddc21f22ea712349497c42e65fd639679dacab4b0192b6664736f6c63430008160033";
  readonly deployedBytecode: "0x60806040525f80fdfea26469706673582212206ab8317330cd83ba3ddc21f22ea712349497c42e65fd639679dacab4b0192b6664736f6c63430008160033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ImportOZ.sol";
  readonly buildInfoId: "solc-0_8_22-eb8e8a43e7e2b14528ab5d2ed886e7942b419852";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ImportOZ"]: ImportOZ$Type;
    ["contracts/ImportOZ.sol:ImportOZ"]: ImportOZ$Type;
  }
}